#!/usr/bin/env bash

##
## A fake busb for local testing
##

if [ $# -eq 0 ]; then echo "Usage: bsub [fake args]* <eval_command>+"; exit -1; fi

sleep 1

## run last argument which is supposed to be the cmd
## inspired by http://stackoverflow.com/questions/1853946/getting-the-last-argument-passed-to-a-shell-script
for last; do true; done
#echo $last

eval $last

echo "Job <$RANDOM> was submitted"