#!/usr/bin/env bash

##
## A fake busb for local testing
##

if [ $# -eq 0 ]; then echo "Usage: bsub [fake args]* <eval_command>+"; exit -1; fi



sleep 1

echo "Submitted batch job $RANDOM"

# wait to mimic queuing system which also needs some seconds to start a job
sleep 3

## run last argument which is supposed to be the cmd
## see http://stackoverflow.com/questions/1853946/getting-the-last-argument-passed-to-a-shell-script
eval "${@: -1}"

exit 0